;-----------------------------------------------------------------------
include     resources.inc
include     windows.inc

;-----------------------------------------------------------------------
include     kernel32.inc
includelib  kernel32.lib

include     user32.inc
includelib  user32.lib

include     advapi32.inc
includelib  advapi32.lib

;-----------------------------------------------------------------------
include     macros.asm

include     masm32.inc
includelib  masm32.lib

include     slib.inc
includelib  slib.lib

include     blowfish.inc
includelib  blowfish.lib

include     sha256.inc
includelib  sha256.lib

;-----------------------------------------------------------------------
